name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-deploy:
    runs-on: self-hosted  # This tells GitHub Actions to use your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build Docker image for backend
      run: |
        docker build -t maheeraa/backend-app:latest ./backend

    - name: Build Docker image for frontend
      run: |
        docker build -t maheeraa/frontend-app:latest ./frontend

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images to Docker Hub
      run: |
        docker push maheeraa/backend-app:latest
        docker push maheeraa/frontend-app:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
